### ISSUE TITLE
Can be archived?

### ISSUE THREAD

**Issue by esolitos** [nymedia/miniPaint#1]
What is the use of this? The main repo is much more updated than this. Can we rely on the base repo?

This is [10 commits ahead](https://github.com/nymedia/miniPaint/compare/viliusle:miniPaint:master...master), [485 commits behind](https://github.com/nymedia/miniPaint/compare/master...viliusle:miniPaint:master) viliusle:master.

**Comment by eiriksm** [comment]
No I need those 10 commits probably? :)

The use for this is to track the changes I have done to upstream, so that we can update it if we need to do that.

It's also very much in use on a couple sites

**Comment by esolitos** [comment]
👍🏼  Alright, good to know. :)
